# Generated by Django 5.2.5 on 2025-09-13 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_profile_user_type_artist"),
    ]

    operations = [
        migrations.CreateModel(
            name="Competition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("music", "Music"),
                            ("dance", "Dance"),
                            ("comedy", "Comedy"),
                            ("poetry", "Poetry"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "Upcoming"),
                            ("registration_open", "Registration Open"),
                            ("voting_open", "Voting Open"),
                            ("finished", "Finished"),
                        ],
                        default="upcoming",
                        max_length=20,
                    ),
                ),
                (
                    "prize_pool",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "registration_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("voting_end_date", models.DateTimeField()),
                (
                    "organizer",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "organizer"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LivePerformance",
            fields=[
                (
                    "competition",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="finale",
                        serialize=False,
                        to="core.competition",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("venue", models.CharField(max_length=200)),
                ("date_time", models.DateTimeField()),
                ("max_tickets", models.PositiveIntegerField()),
                (
                    "base_ticket_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("finale_nft_token_id", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Contestant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("performance_title", models.CharField(max_length=200)),
                ("performance_video_ipfs_hash", models.CharField(max_length=100)),
                ("is_approved", models.BooleanField(default=False)),
                ("registered_date", models.DateTimeField(auto_now_add=True)),
                (
                    "artist",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "artist"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.profile",
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contestants",
                        to="core.competition",
                    ),
                ),
            ],
            options={
                "unique_together": {("competition", "artist")},
            },
        ),
        migrations.CreateModel(
            name="RevenueDistribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "distribution_type",
                    models.CharField(
                        choices=[
                            ("prize", "Prize to Winner"),
                            ("organizer", "Revenue to Organizer"),
                            ("platform", "Platform Fee"),
                            ("artist_pool", "Pool for Participating Artists"),
                        ],
                        max_length=20,
                    ),
                ),
                ("recipient_wallet", models.CharField(max_length=64)),
                ("transaction_hash", models.CharField(max_length=100)),
                ("distributed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distributions",
                        to="core.competition",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NFTTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("owner_wallet", models.CharField(blank=True, max_length=64)),
                ("token_id", models.CharField(max_length=30, unique=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("sold", "Sold"),
                            ("checked_in", "Checked In"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("mint_date", models.DateTimeField(auto_now_add=True)),
                ("metadata_ipfs_hash", models.CharField(max_length=100)),
                (
                    "performance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="core.liveperformance",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("voter_wallet", models.CharField(max_length=64)),
                ("hcs_message_id", models.CharField(max_length=100)),
                ("voted_at", models.DateTimeField(auto_now_add=True)),
                ("voting_power", models.IntegerField(default=1)),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="core.competition",
                    ),
                ),
                (
                    "contestant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes_received",
                        to="core.contestant",
                    ),
                ),
            ],
            options={
                "unique_together": {("competition", "voter_wallet", "contestant")},
            },
        ),
    ]
