# Generated by Django 5.2.5 on 2025-09-17 09:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NFTCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nft_type",
                    models.CharField(
                        choices=[
                            ("vNFT", "Voting NFT"),
                            ("aNFT", "Artist NFT"),
                            ("pNFT", "Patron NFT"),
                            ("VVIP", "VVIP Ticket"),
                            ("VIP", "VIP Ticket"),
                            ("REG", "Regular Ticket"),
                        ],
                        max_length=4,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "max_supply",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100000),
                        ]
                    ),
                ),
                ("current_supply", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "NFT Collection",
                "verbose_name_plural": "NFT Collections",
            },
        ),
        migrations.RemoveField(
            model_name="competition",
            name="voting_end_date",
        ),
        migrations.AlterField(
            model_name="nftticket",
            name="performance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.liveperformance"
            ),
        ),
        migrations.CreateModel(
            name="TicketTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("vvip", "VVIP"),
                            ("vip", "VIP"),
                            ("regular", "Regular"),
                        ],
                        max_length=10,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.PositiveIntegerField()),
                ("benefits", models.TextField(blank=True)),
                (
                    "performance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.liveperformance",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="nftticket",
            name="tier",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.tickettier",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="NFT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "serial_number",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("owner_wallet", models.CharField(blank=True, max_length=64)),
                ("is_available", models.BooleanField(default=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nfts",
                        to="core.nftcollection",
                    ),
                ),
            ],
            options={
                "ordering": ["collection", "serial_number"],
                "unique_together": {("collection", "serial_number")},
            },
        ),
    ]
