# Generated by Django 5.2.5 on 2025-09-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="hbar",
            field=models.DecimalField(decimal_places=2, default=10, max_digits=9),
        ),
        migrations.AddField(
            model_name="profile",
            name="jmt",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
