# Generated by Django 5.2.5 on 2025-09-13 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profile_user_type_artist"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Artist",
        ),
    ]
